/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.sscmq;
	
import nc.vo.pub.*;
import nc.vo.pub.lang.*;
import java.util.Map;
import java.util.HashMap;
import nc.vo.pub.IVOMeta;
import nc.vo.pubapp.pattern.model.meta.entity.vo.VOMetaFactory;
	
/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:
 * @author 
 * @version NCPrj ??
 */
@SuppressWarnings("serial")
public class InterTransationVO extends SuperVO {
	private transient java.lang.String tranid;
	private transient java.lang.String ttype;
	private transient java.lang.String transtatus;
	private transient java.lang.String memo;
	private transient java.lang.String operator;
	private transient java.lang.String billid;
	private transient java.lang.String billtype;
	private transient java.lang.String transtype;
	private transient java.lang.Object data;
	private transient java.lang.Integer dr = 0;
	private transient nc.vo.pub.lang.UFDateTime ts;


	public static final String TRANID = "tranid";
	public static final String TTYPE = "ttype";
	public static final String TRANSTATUS = "transtatus";
	public static final String MEMO = "memo";
	public static final String OPERATOR = "operator";
	public static final String BILLID = "billid";
	public static final String BILLTYPE = "billtype";
	public static final String TRANSTYPE = "transtype";
	public static final String DATA = "data";
			
	/**
	 * 属性tranid的Getter方法.属性名：操作事务ID
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getTranid () {
		return tranid;
	}   
	/**
	 * 属性tranid的Setter方法.属性名：操作事务ID
	 * 创建日期:
	 * @param newTranid java.lang.String
	 */
	public void setTranid (java.lang.String newTranid ) {
		this.tranid = newTranid;
	} 	  
	/**
	 * 属性ttype的Getter方法.属性名：事务类型
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getTtype () {
		return ttype;
	}   
	/**
	 * 属性ttype的Setter方法.属性名：事务类型
	 * 创建日期:
	 * @param newTtype java.lang.String
	 */
	public void setTtype (java.lang.String newTtype ) {
		this.ttype = newTtype;
	} 	  
	/**
	 * 属性transtatus的Getter方法.属性名：事务状态
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getTranstatus () {
		return transtatus;
	}   
	/**
	 * 属性transtatus的Setter方法.属性名：事务状态
	 * 创建日期:
	 * @param newTranstatus java.lang.String
	 */
	public void setTranstatus (java.lang.String newTranstatus ) {
		this.transtatus = newTranstatus;
	} 	  
	/**
	 * 属性memo的Getter方法.属性名：描述
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getMemo () {
		return memo;
	}   
	/**
	 * 属性memo的Setter方法.属性名：描述
	 * 创建日期:
	 * @param newMemo java.lang.String
	 */
	public void setMemo (java.lang.String newMemo ) {
		this.memo = newMemo;
	} 	  
	/**
	 * 属性operator的Getter方法.属性名：操作者
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getOperator () {
		return operator;
	}   
	/**
	 * 属性operator的Setter方法.属性名：操作者
	 * 创建日期:
	 * @param newOperator java.lang.String
	 */
	public void setOperator (java.lang.String newOperator ) {
		this.operator = newOperator;
	} 	  
	/**
	 * 属性billid的Getter方法.属性名：单据id
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getBillid () {
		return billid;
	}   
	/**
	 * 属性billid的Setter方法.属性名：单据id
	 * 创建日期:
	 * @param newBillid java.lang.String
	 */
	public void setBillid (java.lang.String newBillid ) {
		this.billid = newBillid;
	} 	  
	/**
	 * 属性billtype的Getter方法.属性名：单据类型
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getBilltype () {
		return billtype;
	}   
	/**
	 * 属性billtype的Setter方法.属性名：单据类型
	 * 创建日期:
	 * @param newBilltype java.lang.String
	 */
	public void setBilltype (java.lang.String newBilltype ) {
		this.billtype = newBilltype;
	} 	  
	/**
	 * 属性transtype的Getter方法.属性名：交易类型
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getTranstype () {
		return transtype;
	}   
	/**
	 * 属性transtype的Setter方法.属性名：交易类型
	 * 创建日期:
	 * @param newTranstype java.lang.String
	 */
	public void setTranstype (java.lang.String newTranstype ) {
		this.transtype = newTranstype;
	} 	  
	/**
	 * 属性data的Getter方法.属性名：数据
	 * 创建日期:
	 * @return java.lang.Object
	 */
	public java.lang.Object getData () {
		return data;
	}   
	/**
	 * 属性data的Setter方法.属性名：数据
	 * 创建日期:
	 * @param newData java.lang.Object
	 */
	public void setData (java.lang.Object newData ) {
		this.data = newData;
	} 	  
	/**
	 * 属性dr的Getter方法.属性名：dr
	 * 创建日期:
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getDr () {
		return dr;
	}   
	/**
	 * 属性dr的Setter方法.属性名：dr
	 * 创建日期:
	 * @param newDr java.lang.Integer
	 */
	public void setDr (java.lang.Integer newDr ) {
		this.dr = newDr;
	} 	  
	/**
	 * 属性ts的Getter方法.属性名：ts
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getTs () {
		return ts;
	}   
	/**
	 * 属性ts的Setter方法.属性名：ts
	 * 创建日期:
	 * @param newTs nc.vo.pub.lang.UFDateTime
	 */
	public void setTs (nc.vo.pub.lang.UFDateTime newTs ) {
		this.ts = newTs;
	} 	  
 
	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	    return null;
	}   
    
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "tranid";
	}
    
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "mq_intertransation";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:
	  */
     public InterTransationVO() {
		super();	
	}  
	
	@nc.vo.annotation.MDEntityInfo(beanFullclassName =  "nc.vo.sscmq.InterTransationVO" )
	public IVOMeta getMetaData() {
    	IVOMeta meta = VOMetaFactory.getInstance().getVOMeta("sscinter.InterTransationVO");
   		return meta;
  	}
} 
