/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.sscmq;
	
import nc.vo.pub.*;

/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:
 * @author 
 * @version NCPrj ??
 */
@SuppressWarnings("serial")
public class InterTaskVO extends SuperVO {
	private java.lang.String taskid;
	private java.lang.String taskdesc;
	private java.lang.String tasktype;
	private java.lang.String opertype;
	private java.lang.String opercode;
	private java.lang.String taskstatus;
	private java.lang.String taskresult;
	private java.lang.String billid;
	private java.lang.String taskdatac;
	private java.lang.Object taskdatab;
	private java.lang.String allowundo;
	private java.lang.String sourcetaskid;
	private java.lang.String sourceresult;
	private java.lang.Integer dr = 0;
	private nc.vo.pub.lang.UFDateTime ts;

	public static final String TASKID = "taskid";
	public static final String TASKDESC = "taskdesc";
	public static final String TASKTYPE = "tasktype";
	public static final String OPERTYPE = "opertype";
	public static final String OPERCODE = "opercode";
	public static final String TASKSTATUS = "taskstatus";
	public static final String TASKRESULT = "taskresult";
	public static final String BILLID = "billid";
	public static final String TASKDATAC = "taskdatac";
	public static final String TASKDATAB = "taskdatab";
	public static final String ALLOWUNDO = "allowundo";
	public static final String SOURCETASKID = "sourcetaskid";
	public static final String SOURCERESULT = "sourceresult";
			
	/**
	 * 属性taskid的Getter方法.属性名：任务ID
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getTaskid () {
		return taskid;
	}   
	/**
	 * 属性taskid的Setter方法.属性名：任务ID
	 * 创建日期:
	 * @param newTaskid java.lang.String
	 */
	public void setTaskid (java.lang.String newTaskid ) {
	 	this.taskid = newTaskid;
	} 	  
	/**
	 * 属性taskdesc的Getter方法.属性名：任务描述
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getTaskdesc () {
		return taskdesc;
	}   
	/**
	 * 属性taskdesc的Setter方法.属性名：任务描述
	 * 创建日期:
	 * @param newTaskdesc java.lang.String
	 */
	public void setTaskdesc (java.lang.String newTaskdesc ) {
	 	this.taskdesc = newTaskdesc;
	} 	  
	/**
	 * 属性tasktype的Getter方法.属性名：任务类型
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getTasktype () {
		return tasktype;
	}   
	/**
	 * 属性tasktype的Setter方法.属性名：任务类型
	 * 创建日期:
	 * @param newTasktype java.lang.String
	 */
	public void setTasktype (java.lang.String newTasktype ) {
	 	this.tasktype = newTasktype;
	} 	  
	/**
	 * 属性opertype的Getter方法.属性名：操作类型
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getOpertype () {
		return opertype;
	}   
	/**
	 * 属性opertype的Setter方法.属性名：操作类型
	 * 创建日期:
	 * @param newOpertype java.lang.String
	 */
	public void setOpertype (java.lang.String newOpertype ) {
	 	this.opertype = newOpertype;
	} 	  
	/**
	 * 属性opercode的Getter方法.属性名：操作码
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getOpercode () {
		return opercode;
	}   
	/**
	 * 属性opercode的Setter方法.属性名：操作码
	 * 创建日期:
	 * @param newOpercode java.lang.String
	 */
	public void setOpercode (java.lang.String newOpercode ) {
	 	this.opercode = newOpercode;
	} 	  
	/**
	 * 属性taskstatus的Getter方法.属性名：任务状态
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getTaskstatus () {
		return taskstatus;
	}   
	/**
	 * 属性taskstatus的Setter方法.属性名：任务状态
	 * 创建日期:
	 * @param newTaskstatus java.lang.String
	 */
	public void setTaskstatus (java.lang.String newTaskstatus ) {
	 	this.taskstatus = newTaskstatus;
	} 	  
	/**
	 * 属性taskresult的Getter方法.属性名：任务执行结果
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getTaskresult () {
		return taskresult;
	}   
	/**
	 * 属性taskresult的Setter方法.属性名：任务执行结果
	 * 创建日期:
	 * @param newTaskresult java.lang.String
	 */
	public void setTaskresult (java.lang.String newTaskresult ) {
	 	this.taskresult = newTaskresult;
	} 	  
	/**
	 * 属性billid的Getter方法.属性名：单据id
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getBillid () {
		return billid;
	}   
	/**
	 * 属性billid的Setter方法.属性名：单据id
	 * 创建日期:
	 * @param newBillid java.lang.String
	 */
	public void setBillid (java.lang.String newBillid ) {
	 	this.billid = newBillid;
	} 	  
	/**
	 * 属性taskdatac的Getter方法.属性名：任务数据字符串
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getTaskdatac () {
		return taskdatac;
	}   
	/**
	 * 属性taskdatac的Setter方法.属性名：任务数据字符串
	 * 创建日期:
	 * @param newTaskdatac java.lang.String
	 */
	public void setTaskdatac (java.lang.String newTaskdatac ) {
	 	this.taskdatac = newTaskdatac;
	} 	  
	/**
	 * 属性taskdatab的Getter方法.属性名：任务数据字节
	 * 创建日期:
	 * @return java.lang.Object
	 */
	public java.lang.Object getTaskdatab () {
		return taskdatab;
	}   
	/**
	 * 属性taskdatab的Setter方法.属性名：任务数据字节
	 * 创建日期:
	 * @param newTaskdatab java.lang.Object
	 */
	public void setTaskdatab (java.lang.Object newTaskdatab ) {
	 	this.taskdatab = newTaskdatab;
	} 	  
	/**
	 * 属性allowundo的Getter方法.属性名：是否允许回滚
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getAllowundo () {
		return allowundo;
	}   
	/**
	 * 属性allowundo的Setter方法.属性名：是否允许回滚
	 * 创建日期:
	 * @param newAllowundo java.lang.String
	 */
	public void setAllowundo (java.lang.String newAllowundo ) {
	 	this.allowundo = newAllowundo;
	} 	  
	/**
	 * 属性sourcetaskid的Getter方法.属性名：来源任务id
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getSourcetaskid () {
		return sourcetaskid;
	}   
	/**
	 * 属性sourcetaskid的Setter方法.属性名：来源任务id
	 * 创建日期:
	 * @param newSourcetaskid java.lang.String
	 */
	public void setSourcetaskid (java.lang.String newSourcetaskid ) {
	 	this.sourcetaskid = newSourcetaskid;
	} 	  
	/**
	 * 属性sourceresult的Getter方法.属性名：來源描述
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getSourceresult () {
		return sourceresult;
	}   
	/**
	 * 属性sourceresult的Setter方法.属性名：來源描述
	 * 创建日期:
	 * @param newSourceresult java.lang.String
	 */
	public void setSourceresult (java.lang.String newSourceresult ) {
	 	this.sourceresult = newSourceresult;
	} 	  
	/**
	 * 属性dr的Getter方法.属性名：dr
	 * 创建日期:
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getDr () {
		return dr;
	}   
	/**
	 * 属性dr的Setter方法.属性名：dr
	 * 创建日期:
	 * @param newDr java.lang.Integer
	 */
	public void setDr (java.lang.Integer newDr ) {
	 	this.dr = newDr;
	} 	  
	/**
	 * 属性ts的Getter方法.属性名：ts
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getTs () {
		return ts;
	}   
	/**
	 * 属性ts的Setter方法.属性名：ts
	 * 创建日期:
	 * @param newTs nc.vo.pub.lang.UFDateTime
	 */
	public void setTs (nc.vo.pub.lang.UFDateTime newTs ) {
	 	this.ts = newTs;
	} 	  
 
	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	    return null;
	}   
    
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "taskid";
	}
    
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "mq_intertaskvo";
	}    
	
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public static java.lang.String getDefaultTableName() {
		return "mq_intertaskvo";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:
	  */
     public InterTaskVO() {
		super();	
	}    
	
	@nc.vo.annotation.MDEntityInfo(beanFullclassName =  "nc.vo.sscmq.InterTaskVO" )
	public IVOMeta getMetaData() {
   		return null;
  	}
} 


